services:  
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /mnt/ssd/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /mnt/ssd/docker/containers:/var/lib/docker/containers:ro
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    restart: always