version: '3.8'

services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-2
    volumes:
      - ./fluent-bit/fluent-bit.conf:/etc/fluent-bit/fluent-bit.conf:ro
      - ./fluent-bit/trim_log.lua:/etc/fluent-bit/trim_log.lua:ro
      - /home/ubuntu/log:/var/log/app:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: careerbee/fluent-bit
        awslogs-stream: gce/fluent-bit
    restart: always