services:
  ai-server:
    image: ${ECR_REGISTRY}/ai-server:${TAG}
    container_name: ai-server
    network_mode: host
    restart: always
    env_file:
      - /home/ubuntu/.env
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: gce/{{.Name}}