version: '3.8'

services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: fluent-bit
        awslogs-stream: SERVICE-fluent-bit-$(date +%Y-%m-%d)
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf.tpl:/fluent-bit.conf.tpl
      - /var/log:/var/log
    environment:
      - AWS_REGION=ap-northeast-2
    restart: always
    command: >
      /bin/sh -c "envsubst < fluent-bit.conf.tpl > fluent-bit.conf && fluent-bit -c fluent-bit.conf"
    