[SERVICE]
  Flush        15
  Daemon       Off
  Log_Level    info

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[OUTPUT]
  Name cloudwatch_logs
  Match service/*
  region ap-northeast-2
  log_group_name careerbee/service
  log_stream_prefix service/
  auto_create_group true

[INPUT]
  Name   tail
  Path   /var/log/cloud-init-output.log
  Tag    log.startup
  DB     /var/log/flb_tail_startup.db
  Read_from_Head true

[OUTPUT]
  Name cloudwatch_logs
  Match log.startup
  region ap-northeast-2
  log_group_name careerbee/service
  log_stream_name service/startup
  auto_create_group true