- name: Initialize kubeadm
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create join.sh
  shell: |
    kubeadm token create --print-join-command > /tmp/join.sh
    chmod +x /tmp/join.sh
    aws s3 cp /tmp/join.sh s3://s3-careerbee-dev-infra/kube/join.sh

- name: Set up kubeconfig for root user
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config

- name: Check if helm is installed
  command: which helm
  register: helm_check
  ignore_errors: true

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_check.rc != 0

- name: Install Helm
  command: /tmp/get_helm.sh
  when: helm_check.rc != 0

- name: Check if Calico is already installed
  shell: helm list -n tigera-operator | grep calico
  register: calico_check
  ignore_errors: true
  changed_when: false

- name: Add Calico Helm repository
  community.kubernetes.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts
  when: calico_check.rc != 0

- name: Install Calico via Helm
  community.kubernetes.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    chart_version: "v3.30.2"
    release_namespace: tigera-operator
    create_namespace: true
    wait: true
    timeout: 300s
    values:
      installation:
        calicoNetwork:
          nodeAddressAutodetectionV4:
            skipInterface: "tailscale.*"
  when: calico_check.rc != 0

- name: Wait for Calico-node pods to be created
  shell: kubectl get pods -n calico-system -l k8s-app=calico-node --no-headers
  register: calico_pods_check
  until: calico_pods_check.stdout != ""
  retries: 30
  delay: 10
  changed_when: false
  when: calico_check.rc != 0

- name: Wait until Calico-node pods are ready
  shell: kubectl wait --for=condition=Ready pod -l k8s-app=calico-node -n calico-system --timeout=300s
  register: calico_wait
  changed_when: false
  failed_when: calico_wait.rc != 0
  when: calico_check.rc != 0

- name: Load Terraform output from JSON
  set_fact:
    tf_output: "{{ lookup('file', 'tf_output.json') | from_json }}"