services:
  mysql:
    image: mysql:8.4.0
    container_name: replica
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /home/ubuntu/mysql/conf/replica.cnf:/etc/mysql/conf.d/replica.cnf
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: db/{{.Name}}
    restart: always