services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /home/ubuntu/mysql/conf:/etc/mysql/conf.d
      - /home/ubuntu/log:/var/log/mysql
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/etc/fluent-bit/fluent-bit.conf:ro
      - /home/ubuntu/log:/var/log/app:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: careerbee/fluent-bit
        awslogs-stream: mysql/fluent-bit
    restart: always