services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /home/ubuntu/mysql/conf:/etc/mysql/conf.d
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: db/{{.Name}}
    restart: always
      
  redis:
    image: redis:6.2.14
    container_name: redis
    network_mode: host
    volumes:
      - /home/ubuntu/redis/data:/data
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: db/{{.Name}}
    restart: always

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    network_mode: host
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/log/cloud-init-output.log:/var/log/cloud-init-output.log:ro
    restart: always