server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-infra
    static_configs:
      - targets: ['localhost']
        labels:
          job: system-infra
          __path__: /var/log/cloud-init-output.log
          
  - job_name: promtail-infra
    static_configs:
      - targets: ['localhost']
        labels:
          job: promtail-infra
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="promtail-infra"}'
          stages:
            - regex:
                expression: '^.* (promtail)(?:\[\d+\])?: .*'
            - output:
                source: entry

  - job_name: loki
    static_configs:
      - targets: ['localhost']
        labels:
          job: loki
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="loki"}'
          stages:
            - regex:
                expression: '^.* (loki)(?:\[\d+\])?: .*'
            - output:
                source: entry

  - job_name: prometheus
    static_configs:
      - targets: ['localhost']
        labels:
          job: prometheus
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="prometheus"}'
          stages:
            - regex:
                expression: '^.* (prometheus)(?:\[\d+\])?: .*'
            - output:
                source: entry

  - job_name: node-exporter-infra
    static_configs:
      - targets: ['localhost']
        labels:
          job: node-exporter-infra
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="node-exporter-infra"}'
          stages:
            - regex:
                expression: '^.* (node-exporter)(?:\[\d+\])?: .*'
            - output:
                source: entry

  - job_name: grafana
    static_configs:
      - targets: ['localhost']
        labels:
          job: grafana
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="grafana"}'
          stages:
            - regex:
                expression: '^.* (grafana)(?:\[\d+\])?: .*'
            - output:
                source: entry

  - job_name: webhook
    static_configs:
      - targets: ['localhost']
        labels:
          job: webhook
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="webhook"}'
          stages:
            - regex:
                expression: '^.* (webhook)(?:\[\d+\])?: .*'
            - output:
                source: entry

  - job_name: nginx
    static_configs:
      - targets: ['localhost']
        labels:
          job: nginx
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="nginx"}'
          stages:
            - regex:
                expression: '^.* (nginx)(?:\[\d+\])?: .*'
            - output:
                source: entry