server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-infra
    static_configs:
      - targets: ['localhost']
        labels:
          job: system-infra
          __path__: /var/log/cloud-init-output.log