global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ai-server'
    static_configs:
      - targets: ['10.0.110.10:8000']
  
  - job_name: 'vllm'
    static_configs:
      - targets: ['10.0.110.10:8001']

  - job_name: 'frontend'
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 5173
        filters:
          - name: "tag:Name"
            values: ["asg-careerbee-dev-service"]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: $1:5173

  - job_name: 'backend'
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8080
        filters:
          - name: "tag:Name"
            values: ["asg-careerbee-dev-service"]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: $1:8080

  - job_name: 'node-exporter-service'
    ec2_sd_configs:
      - region: ap-northeast-2  # 리전에 맞게 수정
        port: 9100              # node_exporter가 열려 있는 포트
        filters:
          - name: "tag:Name"
            values: ["asg-careerbee-dev-service"]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: __address__
        replacement: $1:9100

  - job_name: 'node-exporter-gce'
    static_configs:
      - targets: ['10.0.110.10:9100']

  - job_name: 'node-exporter-infra'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'node-exporter-db'
    static_configs:
      - targets: ['192.168.210.10:9100']

  - job_name: 'node-exporter-replica'
    static_configs:
      - targets: ['192.168.210.20:9100']

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['10.0.110.10:9400']