[mysqld]
# 네트워크 설정
bind-address = 0.0.0.0

# 문자셋 설정
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

# 로그 설정
log-error = /var/log/mysql/error.log
general_log = 1
general_log_file = /var/log/mysql/general.log

# 복제(Replica용)
server-id = 2
relay-log = relay-log
gtid_mode = ON
enforce-gtid-consistency = ON
read-only = ON
log-slave-updates = ON