version: '3.8'

services:
  nginx:
    image: nginx:latest
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: nginx
        awslogs-stream: SERVICE-nginx-$(date +%Y-%m-%d)
    container_name: nginx-proxy-service
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always