services:
  frontend:
    image: ${ECR_REGISTRY}/frontend:${TAG}
    container_name: frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/log:/var/log/app
    command: ["nginx", "-g", "daemon off;"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: always

  backend:
    image: ${ECR_REGISTRY}/backend:${TAG}
    container_name: backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/scouter:/scouter
      - /home/ubuntu/log:/var/log/app
    command: [
      "java",
      "-Dspring.profiles.active=dev",
      "-javaagent:/scouter/agent.java/scouter.agent.jar",
      "-Dscouter.config=/scouter/agent.java/conf/scouter.conf",
      "-Dobj_name=careerbee-api",
      "-Duser.timezone=Asia/Seoul",
      "--add-opens", "java.base/java.lang=ALL-UNNAMED",
      "--add-exports", "java.base/sun.net=ALL-UNNAMED",
      "-Djdk.attach.allowAttachSelf=true",
      "-jar", "careerbee-api.jar"
    ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    env_file:
      - /home/ubuntu/.env