services:
  frontend:
    image: ${ECR_REGISTRY}/frontend:${TAG}
    container_name: frontend
    ports:
      - "5173:80"
    restart: always
    env_file:
      - ../.env
    volumes:
      - /home/ubuntu/frontend:/usr/share/nginx/html
  backend:
    image: ${ECR_REGISTRY}/backend:${TAG}
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/scouter:/scouter
      - /home/ubuntu/log:/var/log/app
    environment:
      - JAVA_TOOL_OPTIONS=-Dspring.profiles.active=dev \
        -javaagent:/scouter/agent.java/scouter.agent.jar \
        -Dscouter.config=/scouter/agent.java/conf/scouter.conf \
        -Dobj_name=careerbee-api \
        -Duser.timezone=Asia/Seoul \
        --add-opens java.base/java.lang=ALL-UNNAMED \
        --add-exports java.base/sun.net=ALL-UNNAMED \
        -Djdk.attach.allowAttachSelf=true
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "java $JAVA_TOOL_OPTIONS -jar careerbee.jar 2>&1 | tee /var/log/app/backend.log"
    restart: always
    env_file:
      - ../.env