- name: Apply ArgoCD applications
  vars:
    apps:
      - fe.yml
      - be.yml
      - ai.yml
  kubernetes.core.k8s:
    state: present
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/files/apps/' + item) | from_yaml }}"
  loop: "{{ apps }}"
  loop_control:
    label: "{{ item }}"