services:
  mysql:
    image: mysql:8.4.0
    container_name: replica
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /home/ubuntu/mysql/conf/replica.cnf:/etc/mysql/conf.d/replica.cnf
    restart: always

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /home/ubuntu/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: always