- name: Check if ALB Controller is already installed
  shell: helm list -n kube-system | grep aws-load-balancer-controller
  register: alb_check
  ignore_errors: true
  changed_when: false

- name: Add EKS Helm repo
  community.kubernetes.helm_repository:
    name: eks
    repo_url: https://aws.github.io/eks-charts
  when: alb_check.rc != 0

- name: Apply ALB Controller CRDs
  shell: |
    kubectl apply -k "github.com/kubernetes-sigs/aws-load-balancer-controller/config/crd?ref=v2.7.1"
  when: alb_check.rc != 0
    
- name: Install ALB Ingress Controller via Helm
  community.kubernetes.helm:
    name: aws-load-balancer-controller
    chart_ref: eks/aws-load-balancer-controller
    release_namespace: kube-system
    create_namespace: false
    values:
      clusterName: "{{ tf_output.prefix.value }}"
      region: "{{ tf_output.aws_region.value }}"
      vpcId: "{{ tf_output.aws_vpc_id.value }}"
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
      enableCertManager: false
      enableAdmissionWebhook: true
      enableServiceMutatorWebhook: false
      enableWAFv2: true
      enableShield: true
    wait: true
    timeout: 300s
  when: alb_check.rc != 0