- name: Add EKS Helm repo
  community.kubernetes.helm_repository:
    name: eks
    repo_url: https://aws.github.io/eks-charts

- name: Apply ALB Controller CRDs
  shell: |
    kubectl apply -k "github.com/kubernetes-sigs/aws-load-balancer-controller/config/crd?ref=v2.7.1"
    
- name: Install ALB Ingress Controller via Helm
  community.kubernetes.helm:
    name: aws-load-balancer-controller
    chart_ref: eks/aws-load-balancer-controller
    release_namespace: kube-system
    create_namespace: false
    values:
      clusterName: "{{ tf_output.prefix.value }}"
      region: "{{ tf_output.aws_region.value }}"
      vpcId: "{{ tf_output.aws_vpc_id.value }}"
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
      enableCertManager: false
      enableAdmissionWebhook: true
      annotations:
        alb.ingress.kubernetes.io/certificate-arn: "{{ tf_output.acm_arn.value }}"
    wait: true
    timeout: 300s