- name: Add EKS Helm repo
  community.kubernetes.helm_repository:
    name: eks
    repo_url: https://aws.github.io/eks-charts

- name: Install cert-manager
  shell: |
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml

- name: Apply ALB Controller CRDs
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml

- name: Create namespace for kube-system
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-system

- name: Install ALB Ingress Controller via Helm
  community.kubernetes.helm:
    name: aws-load-balancer-controller
    chart_ref: eks/aws-load-balancer-controller
    release_namespace: kube-system
    create_namespace: false
    values:
      clusterName: "{{ tf_output.prefix.value }}"
      region: "{{ tf_output.aws_region.value }}"
      vpcId: "{{ tf_output.aws_vpc_id.value }}"
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
    wait: true
    timeout: 300s