- name: Add ArgoCD Helm repository
  community.kubernetes.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Create namespace for ArgoCD
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: Load Terraform output from JSON
  set_fact:
    tf_output: "{{ lookup('file', 'tf_output.json') | from_json }}"

- name: Install or upgrade ArgoCD via Helm
  community.kubernetes.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    values_files:
      - "{{ playbook_dir }}/files/argocd/values.yml"
    create_namespace: false
    wait: true
    atomic: true

- name: Wait for ArgoCD server rollout
  shell: kubectl -n argocd rollout status deployment argocd-server
  register: rollout_status
  until: rollout_status.rc == 0
  retries: 10
  delay: 10

- name: Set ArgoCD admin password
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
        namespace: argocd
      type: Opaque
      stringData:
        admin.password: "{{ tf_output.argocd_admin_password_hash.value }}"
        admin.passwordMtime: "{{ lookup('pipe', 'date +%FT%T%Z') }}"