version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: mysql
        awslogs-stream: DB-mysql-$(date +%Y-%m-%d)
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: always

volumes:
  mysql_data: