services:
  frontend:
    image: ${ECR_REGISTRY}/frontend:${TAG}
    container_name: frontend
    network_mode: host
    platform: linux/amd64
    ports:
      - "80:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: service/{{.Name}}
    restart: always