services:
  webhook:
    build: ./webhook
    container_name: webhook
    ports:
      - "5000:5000"
    volumes:
      - ./deploy.sh:/deploy/deploy.sh
      - ./webhook:/app
      - /home/ubuntu/log:/var/log/app
      - /var/run/docker.sock:/var/run/docker.sock  # 컨테이너 내에서 docker 명령 실행 가능
    working_dir: /app
    command: ["python", "webhook.py"]
    environment:
      - ECR_REGISTRY=${ECR_REGISTRY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    networks:
      - app-network

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/etc/fluent-bit/fluent-bit.conf:ro
      - /home/ubuntu/log:/var/log/app:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: fluent-bit
        awslogs-stream: service/fluent-bit
    restart: always

networks:
  app-network:
    external: true
    name: app-network