services:
  frontend:
    image: ${ECR_REGISTRY}/frontend:${TAG}
    container_name: frontend
    platform: linux/amd64
    ports:
      - "5173:5173"
    restart: always

  backend:
    image: ${ECR_REGISTRY}/backend:${TAG}
    container_name: backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    command: [
      "java",
      "-Dspring.profiles.active=dev",
      "-Dobj_name=careerbee-api",
      "-Duser.timezone=Asia/Seoul",
      "--add-opens", "java.base/java.lang=ALL-UNNAMED",
      "--add-exports", "java.base/sun.net=ALL-UNNAMED",
      "-Djdk.attach.allowAttachSelf=true",
      "-jar", "careerbee-api.jar"
    ]
    restart: always
    env_file:
      - /home/ubuntu/.env

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /home/ubuntu/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: always