services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always

  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - /home/ubuntu/loki/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /home/ubuntu/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always
    
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${DB_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always

  webhook:
    container_name: webhook
    build: ./webhook
    volumes:
      - .:/app
      - /home/ubuntu/.env:/home/ubuntu/.env:ro
      - /home/ubuntu/.ssh/id_rsa:/home/ubuntu/.ssh/id_rsa:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "webhook.py"]
    environment:
      - ECR_REGISTRY=${ECR_REGISTRY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MOUNT_DIR=${MOUNT_DIR}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
    working_dir: /app/webhook
    ports:
      - "5000:5000"
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}"
    restart: always