name: Self-Hosted Test

on:
  push:
    branches: [ develop ]

jobs:
  test-runner:
    runs-on: [self-hosted, linux, gce-ssmu-dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test script
        run: echo "Self-hosted runner is working!"
