server {
    listen 80 default_server;
    server_name ai.dev.careerbee.co.kr;

    location / {
        proxy_pass http://10.0.110.10:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}